{% set name = "rq" %}
{% set version = "0.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/nvie/rq/archive/v{{ version }}.tar.gz
  sha256: eadd013206a258dbb91673f54d8ab70eeedf77107dd547ba2af166a970586bc3

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  build:
    - python
    - pip
    - redis-py >=2.7.0
    - click >=3.0

  run:
    - python
    - setuptools
    - redis-py >=2.7.0
    - click >=3.0

test:
  imports:
    - rq
    - rq.cli
    - rq.compat
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://github.com/nvie/rq/
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'RQ is a simple, lightweight, library for creating background jobs, and processing them.'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
