{% set name = "rq" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22de332ed7e061634eb893dc8cc9ca96c8641480f46c403cabef8d43a2eca867

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  host: 
    - python
    - pip

  run:
    - python
    - setuptools
    - redis-py >=3.0.0
    - click >=5.0

test:
  imports:
    - rq
    - rq.cli
    - rq.compat
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://python-rq.org/ 
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'RQ is a simple, lightweight, library for creating background jobs, and processing them.'
  doc_url: https://python-rq.org/docs/
  dev_url: https://github.com/rq/rq

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jkornblum
