{% set name = "rq" %}
{% set version = "0.10.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version}}.tar.gz
  url: https://github.com/nvie/rq/archive/v{{ version }}.tar.gz
  sha256: 71fb6a14354013106655efd3eccd028fcea81f1dab0aaf14ecb26ec15ebd4bfc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  build:
    - python
    - setuptools
    - redis-py >=2.7.0
    - click >=3.0

  run:
    - python
    - setuptools
    - redis-py >=2.7.0
    - click >=3.0

test:
  imports:
    - rq
    - rq.cli
    - rq.compat
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://github.com/nvie/rq/
  license: BSD 2-Clause
  summary: 'RQ is a simple, lightweight, library for creating background jobs, and processing them.'

extra:
  recipe-maintainers:
    - kwilcox
    - daf
