travis:
  secure:
    BINSTAR_TOKEN: ChhpBeL0g7/OiIco8BbTrN9mKbfD+mCanu415rWsbQnCb0F9O6PwEvAEjzBohdIrsht6Kab3yH/4HC90vqik6UesHxfGvtJk/0EpxJrckJOk8MauUo1XXwZHm1fCDnoRThS2PnfG7CCF/iCmJpZ8dzfMc8ZEQUf8HyudJiG+6pPhNGqNaEW5bWnXMUYEbKRN6aSORM05wjcCvj6DrKHrpE1FpZbOrfP0XBsjrfCBKHt6C0Fu20NWnwJ8lWFSNPNSjzXtmH/IYB4nkneG75H40kDhdXJNhE9/zUegcDSYRMN/94i1xqJV3BnAsNUXo8oS/vdtNUhHD6BR3A4IFyGTPt1U2KONnhyobMBEkRf5IIPKs7CidVwlqk8z+ZqWvsgUXI+c6koVw/vfvfylJ1J9Mygj3qxJ58HC1byRvEkepaIl8ds24xvb69fqlosnTLdA7P+0oJg8v8+kZydIytGRR5fEjgdnAm8aKApnRLWhpAO2+zwOoyKzf+R2wNwlSYiLAxxyWCz0HOakRLGZJ115kDtEz5j9hpVrXz/Ka1ZvfN2NOMXB3GEKc+Yq/AXFtlPSYh8Ujwk2k5+q8Zz1KVCOffW5nMvA14iNAk73Kxbj6+ZBIrnarMInZJXxtt3StYOyYnLm4BBEUDjIqQEYbfoMczaLlbvIiaNucAM/j8BmgFM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
