travis:
  secure:
    BINSTAR_TOKEN: BUmGh8kg0eierUy7XdBJn6HECxH8euqh4nLDWwuDtdIC6W4LyIhlDUV32WE2tnY/h3XE5iBatqB63YRc+4PPOv+mvoaC+Va1XLpp9e5IEpPJ0KiIlgXjyfPEuJxQ+Z6TeDfoeBpVbdG1S+CTmIKU7gPvx63w34vxH1Me0iZzIIx3JB4kh5ZpVYXtq48AegPRQJs6moRn7QZsr0bR71cRZC3YtaaCwjwr8EQKI+uMjJQeIvq4l1w+rp7gFelKwpDdjBzCKf2YwEoO67EeZaSe0y2DtXUEV0qatRUsr7XM9QEvzhDtoIp0LP7aQuVpUYHHpnLHsyshb8zNN8TQwVGO4bbiiIRSY5zO/xhZRAgKU6HY1tj0sSr9BUeR5gQZa6ZdW81sUfG955NH9yj5af0JS5uSfI/XohRoQeZL9CroEqBA/4a16lo12xeJWiSIRBUENAS0kzV/z9OVGf7J1qt8VPODG8J4XS5AKKldf2rHuYCPjksqWqr1T9rz8QHjemIp7rUvb/AV3YIQ3HHBNDKeh7Lkd9STXHsRTJiwruRneIwmCBuHbPALnodAyT3CDGDGIYyhoHze4B7cnXmMNBxvTZw9U49ZLkmSY5EE87L33MVVcCRpDrhcK8niVaLLpyb4w7VTXn76ChOJfC8o5Ncl0tv5WMyNFkWXx8DfDUnaP1o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
