travis:
  secure:
    BINSTAR_TOKEN: n7ppSwn65BG8x3beVvv1ZTEDHcflFI6NSnCsjuB1IzU9QIfR7EVtM9gL+Ga3hZk9yQtyN/VdbNgiELKefbKQILtPD7cEAhMWhbtj82V6RgKomqOgB4dBHP9eTSOgmhh+a9+Bk39jKN1rZ+1sKwCnPcLTZPKg0qWh2KvJtSTAEl1D6wF4HmYu8QyoTEcK2oSftySZI68r/l8kcZr1s48qABiYVDCZX5uTNdQs/4gI4wag0cazOkrZpvpeXxqPekclZDOrDa9l70R/KwnEjYTo+kbC8yZZRDgcSa8B44kXdc2m7Y7bMF3zwVOft54F38HJVpY52Ag3QYb9D1Ju5GWI+1AQ5UO30XNgNi0Zt33xrAVQQrm4A+mByGJJ0QRxpE5tDQ+/H9AfLYl0P0yS57T1RODFC+II9BbX8MY/h1RcxMMuWarng50jO72Lcn0DeWlgvFbzM7KfRudDwDiftkls7H5AHqNYc9IKbZBOJeiJcW/nXuQDcXYvajnWqPpqWsU2d373o9s5wqwTIU1PLCXZN/1iilUUIV8zmGK2rLYPDRZqEqhvcERiJTAZeglDGlK6ek30eOsX+b48LMlxf/xXE0JB5bUgFIq9hQwH/GatZCUzXQ3g+i+AzKfRRtYllqY/Zfife/Pay/SXgjClTNw8ZDikJaak5aeLF9r0aGpZjFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
